### ISSUE TITLE
Word Corrupt Doc Checker Reports Fixing a File That Won't Open in Word 2016

### ISSUE THREAD

**Issue by socrtwo** [desjarlais/wordcorruptdocchecker#2]
Word Corrupt Doc Checker reports fixing a file I will privately share with the author. It reports:
`Invalid Tag: </w:txbxContent></w:pict></mc:Fallback></mc:AlternateContent>
Replaced With: </w:txbxContent></v:textbox></v:shape></w:pict></mc:Fallback></mc:AlternateContent>`

The fixed file won't open in Word 2016, but will open if the </v:shape> tag is replaced with a </v:rect> one.

**Comment by desjarlais** [comment]
Thanks for the report.  The reason the default Fix fails is because the code I wrote is assuming the textbox (txbxContent) is a shape, not a rectangle.  I'll see if I can adjust the logic to handle both shape and rectangle scenarios. 

The option that should work (and likely works on almost all of these type of corrupt files) is the "Remove all fallback" tags option.  If you check that box and attempt to fix the original file, it should work correctly.  

The reason that works is because I'm taking a brute force approach of deleting all of the fallback tags since they are optional tags per the file format spec.  It is only relevant for older clients who are going to read the file, so technically, it will resolve the problem, but could make down-level clients fail.  That is unless you re-save the file in Word and let it re-populate the fallback tags correctly, which it should.

**Comment by socrtwo** [comment]
Thanks for working on this. Have you released a build with a checkbox to
remove all "Remove all fallback" tags?

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by socrtwo** [comment]
I removed the *<mc:Fallback>* and *</mc:Fallback>* tags from the EXPO
SISTEMAS.docx word\document.xml file and it didn't fix the rezipped
version.

Do you mean the whole line
*</w:txbxContent></w:pict></mc:Fallback></mc:AlternateContent>*? Or do you
mean *<mc:Fallback>* and *</mc:Fallback>* tags and everything between them?
Or something else?

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by desjarlais** [comment]
I let the application do it, which you can do by checking the checkbox on the bottom left corner of the application window and then clicking Fix Document.  Basically I'm removing the entire <mc:Fallback>...</mc:Fallback> block of tags.  You leave the AC (AlternateContent) tag though.

**Comment by socrtwo** [comment]
Yeah, that worked. You can close the bug.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by socrtwo** [comment]
I didn't see that checkbox before but you clearly had it in the current
version as I see now.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.
