### ISSUE TITLE
Corrupt Document is Only Partially Fixed by Program

### ISSUE THREAD

**Issue by socrtwo** [desjarlais/wordcorruptdocchecker#9]
A corrupt document I recently was asked to fix, is partially repaired by the program. The problems seem to revolve around the same usual suspect tags. 

I'm not sure which tags are not being properly addressed. The lack of complete result occurred even when the check box for removing all Fallback check marks was checked. I also ran the files through the program in succession more than one cycle and this didn't seem to help either.

I will send the file to the author separately.

**Comment by desjarlais** [comment]
I have seen this on rare occasions.  When this has happened to me before, it is a bug in the logic I'm using to parse the xml.  There are just times where the tags are in an order that is very similar to something I've coded for, but it is not exactly the same.  This causes the replace in the code to partially fix the xml but it still leaves fragments of the problem still in the file.  If I can see the original problem file before the fix was attempted, I can check and confirm.  Have you sent me the problem document already?

**Comment by socrtwo** [comment]
[Here is the file](https://1drv.ms/w/s!AtqwKV_OsClkg89hM4SQaebKBINbew). Let me know when you get it, so I can remove the link.

**Comment by desjarlais** [comment]
Thanks for the file, I deleted the comment to remove it from the comments.

**Comment by socrtwo** [comment]
Cool. Thanks.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by desjarlais** [comment]
Thanks for the report and document.  This corruption of tags definitely isn't something I'm catching.  

I'll need to think about this one and see what I can come up with to add this to the tool, I'll need a few days to investigate.

**Comment by socrtwo** [comment]
Sounds good. Glad the file helps improving things. I "fixed" the file by
removing the whole first paragraph which contained the front cover first
page and all those fallback tags and such.

Best Wishes,

Paul D Pruitt

socrtwo@s2services.com
(301) 493-4982
9006 Friars Rd.
Bethesda, MD  20817-3320

   - Have a manuscript lying around gathering dust? Let me help you
   self-publish it <socrtwo@s2services.com>.

**Comment by desjarlais** [comment]
Closing this issue...unfortunately, I won't be able to make this change.
